src/Meeting/Weekend/Entity/Program.php
<?php

namespace App\Meeting\Weekend\Entity;

use App\Meeting\Weekend\Repository\ProgramRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use App\Core\Entity\User;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="weekend_program")
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Entity(repositoryClass=ProgramRepository::class)
 */
class Program
{
    const VALIDATED = 2;
    const DRAFT = 1;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Valid()
     * @Groups({"show"})
     * @ORM\OneToMany(targetEntity=Weekend::class, mappedBy="program", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $weekends;

    /**
     * @Groups({"show"})
     * @ORM\Column(type="datetime")
     */
    private $startDate;

    /**
     * @Groups({"show"})
     * @ORM\Column(type="datetime")
     */
    private $endDate;

    /**
     * @Groups({"show"})
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @Groups({"show"})
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;


    /**
     * @ORM\Column(type="boolean")
     */
    private $draft = false;


    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $user;

    public function __construct()
    {
        $this->weekends = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }



    /**
     * @return Collection|Weekend[]
     */
    public function getWeekends(): Collection
    {
        return $this->weekends;
    }

    public function addWeekend(Weekend $weekend): self
    {
        if (!$this->weekends->contains($weekend)) {
            $this->weekends[] = $weekend;
            $weekend->setProgram($this);
        }

        return $this;
    }

    public function removeWeekend(Weekend $weekend): self
    {
        if ($this->weekends->removeElement($weekend)) {
            // set the owning side to null (unless already changed)
            if ($weekend->getProgram() === $this) {
                $weekend->setProgram(null);
            }
        }

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        $this->created_at = new \DateTime();
    }

    /**
     * @ORM\PreUpdate()
     */
    public function setUpdatedAtValue()
    {
        $this->updated_at = new \DateTime();
    }

    public function getUser(): ?UserInterface
    {
        return $this->user;
    }

    public function setUser(?UserInterface $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return bool
     */
    public function isDraft(): bool
    {
        return $this->draft;
    }

    /**
     * @param bool $draft
     */
    public function setDraft(bool $draft): void
    {
        $this->draft = $draft;
    }



}

src/Meeting/Weekend/Entity/Weekend.php
<?php

namespace App\Meeting\Weekend\Entity;

use App\Meeting\Weekend\Repository\WeekendRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use App\Meeting\Weekend\Validator as MeetingWeekendValidator;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @MeetingWeekendValidator\IsValid()
 * @ORM\Table(name="weekend")
 * @ORM\Entity(repositoryClass=WeekendRepository::class)
 */
class Weekend
{
    const TYPE_OVERSEER = 'overseer';
    const TYPE_EXTERNAL_SPEAKER = 'external_speaker';
    const TYPE_CONVENTION = 'convention';
    const TYPE_OUTGOING_SPEAKER = 'outgoing';
    const TYPE_CONVENTION_FRIDAY_MORNING = 'convention_friday_morning';
    const TYPE_CONVENTION_FRIDAY_AFTERNOON = 'convention_friday_afternoon';
    const TYPE_CONVENTION_SATURDAY_MORNING = 'convention_saturday_morning';
    const TYPE_CONVENTION_SATURDAY_AFTERNOON = 'convention_saturday_afternoon';
    const TYPE_CONVENTION_SUNDAY_MORNING = 'convention_sunday_morning';
    const TYPE_CONVENTION_SUNDAY_AFTERNOON = 'convention_sunday_afternoon';

    /**
     * @Groups({"show"})
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Program::class, inversedBy="weekends", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $program;

    /**
     * @Groups({"show"})
     * @var Speaker
     * @ORM\ManyToOne(targetEntity=Speaker::class, inversedBy="weekends")
     * @ORM\JoinColumn(nullable=true)
     */
    private $speaker;

    /**
     * @Groups({"show"})
     * @var Reader
     * @ORM\ManyToOne(targetEntity=Reader::class, inversedBy="weekends")
     * @ORM\JoinColumn(nullable=true)
     */
    private $reader;

    /**
     * @Groups({"show"})
     * @var Chairman
     * @ORM\ManyToOne(targetEntity=Chairman::class, inversedBy="weekends")
     * @ORM\JoinColumn(nullable=true)
     */
    private $chairman;

    /**
     * @Groups({"show"})
     * @var Speech
     * @ORM\ManyToOne(targetEntity=Speech::class, inversedBy="weekends")
     * @ORM\JoinColumn(nullable=true)
     */
    private $speech;

    /**
     * @Groups({"show"})
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date;

    /**
     * @Groups({"show"})
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     */
    private $external_name;


    /**
     * @Groups({"show"})
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $overseer_name;

    /**
     * @var string
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $type;

    /**
     * @Assert\Valid()
     * @ORM\OneToMany(targetEntity=OutgoingSpeech::class, mappedBy="weekend", cascade={"persist"})
     */
    private $outgoingSpeeches;

    public function __construct()
    {
        $this->outgoingSpeeches = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProgram(): ?Program
    {
        return $this->program;
    }

    public function setProgram(?Program $program): self
    {
        $this->program = $program;

        return $this;
    }

    public function getSpeaker(): ?Speaker
    {
        return $this->speaker;
    }

    public function setSpeaker(?Speaker $speaker): self
    {
        if ($this->type != self::TYPE_EXTERNAL_SPEAKER || $this->type != self::TYPE_OVERSEER) {
            $this->speaker = $speaker;
        }


        return $this;
    }

    public function getReader(): ?Reader
    {
        return $this->reader;
    }

    public function setReader(?Reader $reader): self
    {
        $this->reader = $reader;

        return $this;
    }

    /**
     * @return Chairman|null
     */
    public function getChairman(): ?Chairman
    {
        return $this->chairman;
    }

    public function setChairman(?Chairman $chairman): self
    {
        $this->chairman = $chairman;

        return $this;
    }

    public function getSpeech(): ?Speech
    {
        return $this->speech;
    }

    public function setSpeech(?Speech $speech): self
    {
        $this->speech = $speech;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate($date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getExternalName(): ?string
    {
        return $this->external_name;
    }

    public function setExternalName(?string $external_name): self
    {
        $this->external_name = $external_name;

        return $this;
    }


    public function getOverseerName(): ?string
    {
        return $this->overseer_name;
    }

    public function setOverseerName(?string $overseer_name): self
    {
        $this->overseer_name = $overseer_name;

        return $this;
    }

    /**
     * @return string
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * @param string $type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * @return Collection|OutgoingSpeech[]
     */
    public function getOutgoingSpeeches(): Collection
    {
        return $this->outgoingSpeeches;
    }

    public function addOutgoingSpeech(OutgoingSpeech $outgoingSpeech): self
    {
        if (!$this->outgoingSpeeches->contains($outgoingSpeech)) {
            $this->outgoingSpeeches[] = $outgoingSpeech;
            $outgoingSpeech->setWeekend($this);
        }

        return $this;
    }

    public function removeOutgoingSpeech(OutgoingSpeech $outgoingSpeech): self
    {
        if ($this->outgoingSpeeches->removeElement($outgoingSpeech)) {
            // set the owning side to null (unless already changed)
            if ($outgoingSpeech->getWeekend() === $this) {
                $outgoingSpeech->setWeekend(null);
            }
        }

        return $this;
    }
}

src/Meeting/Weekend/Controller/ProgramController.php
<?php


namespace App\Meeting\Weekend\Controller;


use App\Meeting\Weekend\Entity\Program;
use App\Meeting\Weekend\Form\ProgramType;
use App\Meeting\Weekend\Model\ProgramManager;
use App\Meeting\Weekend\Service\DateCalculation;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/dashboard/programs")
 * Class ProgramController
 */
class ProgramController extends AbstractController
{

    private $em;
    /**
     * @var ProgramManager
     */
    private $manager;

    /**
     * @var DateCalculation
     */
    private $dateCalculation;

    public function __construct(EntityManagerInterface $em, ProgramManager $manager, DateCalculation $dateCalculation)
    {
        $this->em = $em;
        $this->manager = $manager;
        $this->dateCalculation = $dateCalculation;
    }

    /**
     * @Route("/save", name="program_save")
     * @param Request $request
     * @return Response
     */
    public function save(Request $request)
    {
        $month = intval($request->query->get('month'));
        $year = intval($request->query->get('year'));
        $saturdays = $this->dateCalculation->getAllSaturdays($month, $year);
        $program = new Program();
        $form = $this->createForm(ProgramType::class, $program);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($request->query->get('draft')) {
                $this->manager->persist($program, true, $this->getUser());
                $this->addFlash('success', 'Programme sauvegardé');
                return $this->redirectToRoute('program_list');
            }

            if ($form->isValid()) {
                $this->manager->persist($program, false, $this->getUser());
                $this->addFlash('success', 'Programme créé');
                return $this->redirectToRoute('program_list');
            }
        }

        return $this->render('meeting/weekend/program/save.html.twig', [
            'form' => $form->createView(),
            'nb_saturdays' => count($saturdays),
            'saturdays' => $saturdays,
        ]);
    }

    /**
     * @Route("/", name="program_list")
     * @return Response
     */
    public function list()
    {
        $repo = $this->getDoctrine()->getRepository(Program::class);

        return $this->render('meeting/weekend/program/list.html.twig', [
            'programs' => $repo->findBy([], ['startDate' => 'ASC'])
        ]);
    }


    /**
     * @Route("/show/{id}", name="program_show")
     * @param Pdf $knpPDF
     * @param Program $program
     * @param Request $request
     * @return Response
     */
    public function show(Pdf $knpPDF, Program $program, Request $request)
    {
        $isPDF = $request->get('pdf');

        if ($isPDF) {
            $timestamp = new \DateTime();
            $html = $this->renderView('meeting/weekend/program/show_pdf.html.twig', [
                'p' => $program
            ]);
            return new PdfResponse($knpPDF->getOutputFromHtml($html), 'program_' . $timestamp->format('dmyHis') . '.pdf');
        }

        if ($request->isXmlHttpRequest()) {
            return $this->render('meeting/weekend/program/_show_ajax.html.twig', [
                'program' => $program
            ]);
        }

        return $this->render('meeting/weekend/program/show.html.twig', [
            'program' => $program
        ]);

    }


    /**
     * @Route("/edit/{id}", name="program_edit")
     * @param Program $program
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function edit(Program $program, Request $request)
    {
        $originalProgram = new ArrayCollection();

        foreach ($program->getWeekends() as $content) {
            $originalProgram->add($content);
        }

        $form = $this->createForm(ProgramType::class, $program);
        $form->handleRequest($request);

        if($form->isSubmitted()) {
            if ($request->query->get('draft')) {
                $this->manager->persist($program, true, $this->getUser());
                $this->addFlash('success', 'Programme sauvegardé');
                return $this->redirectToRoute('program_list');
            }
            if ($form->isValid()) {
                $this->manager->persist($program, false, $this->getUser());
                $this->addFlash('success', 'Programme modifié');
                return $this->redirectToRoute('program_list');
            }
        }

        return $this->render('meeting/weekend/program/edit.html.twig', [
            'form' => $form->createView(),
            'program' => $program
        ]);
    }

    /**
     * @Route("/remove/{id}", name="program_remove")
     * @param Program $program
     */
    public function remove(Program $program)
    {
        $this->em->remove($program);
        $this->em->flush();
        $this->addFlash('success', 'Programme supprimé');
        return $this->redirectToRoute('program_list');
    }


    /**
     * @Route("/validate/{id}", name="program_validate")
     * @param Program $program
     * @return RedirectResponse
     */
    public function validate(Program $program)
    {
        $program->setStatus(Program::VALIDATED);
        $this->em->flush();
        $this->addFlash('notice', 'Le programme a été validé.');
        return $this->redirectToRoute('program_list');

    }

}

src/Meeting/Weekend/Controller/RestProgramController.php
<?php


namespace App\Meeting\Weekend\Controller;


use App\Meeting\Weekend\Entity\Program;
use App\Meeting\Weekend\Entity\Weekend;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;

class RestProgramController extends AbstractController
{
    /** @var SerializerInterface $serializer */
    private $serializer;

    public function __construct(SerializerInterface $serializer)
    {
        $this->serializer = $serializer;
    }


    /**
     * @Route("/rest/programs/last-date")
     * @return Response
     */
    public function getLastDate()
    {
        $date = $this->getDoctrine()->getRepository(Weekend::class)->getLastDate();

        if (!isset($date['date'])) {
            $date = new \DateTime();
            $dateFormatStr = $date->format('Y-m-d');
        } else {
            $date['date']->add(new \DateInterval('P7D'));
            $dateFormatStr = $date['date']->format('Y-m-d');
        }

        $json = $this->serializer->serialize($dateFormatStr, 'json');
        $response = new Response($json);
        $response->headers->set('Content-Type', 'application/json');
        return $response;

    }

    /**
     * @Route("/rest/programs/show/{id}")
     * @param Program $program
     * @return Response
     */
    public function showProgramById(Program $program)
    {
        $json = $this->serializer->serialize($program,
            'json',
            [
                'groups' => 'show'
            ]
        );
        $response = new Response($json);
        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }

}

templates/meeting/weekend/program/_edit_outgoing_speech_modal.twig
<div class="modal fade" id="modalOutgoing{{ index }}"  tabindex="-1" role="dialog" aria-labelledby="modalOutgoing{{ index }}Label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Orateur(s) sortant</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body modal-outgoing"
                 data-prototype="{{ _self.outgoing_prototype(weekend.outgoing.vars.prototype)|e }}"
                 data-weekend-id="{{ index }}"
            >
                {% set id = 0 %}
                {% for outgoing in weekend.outgoing %}
                    <div class="input-group mb-4" id="input-{{ id }}" data-valid="{{ outgoing.vars.valid }}" data-index="{{ index }}">
                        {{ form_widget(outgoing.congregation, {
                            'attr': {'placeholder' : 'Nom de l\'assemblée'}
                            })
                        }}
                        {{ form_widget(outgoing.speaker) }}
                        {{ form_widget(outgoing.speech) }}
                        <a href="#" class="btn btn-outline-danger ml-2 remove-outgoing-speaker"><i class="fas fa-trash"></i></a>
                    </div>
                    {% set id = id + 1 %}
                {% endfor %}
            </div>
            <div class="modal-footer">
                <a href="#" class="add-speaker btn btn-primary" data-weekend-id="{{ index }}">
                    Ajout d'un orateur
                </a>
            </div>
        </div>
    </div>
</div>

{% macro outgoing_prototype(p) %}
    <div class="input-group mb-4">
        {{ form_widget(p.congregation, {
            'attr': {'placeholder' : 'Nom de l\'assemblée'}
        })
        }}
        {{ form_widget(p.speaker) }}
        {{ form_widget(p.speech) }}
        <a href="#" class="btn btn-outline-danger ml-2 remove-outgoing-speaker"><i class="fas fa-trash"></i></a>
    </div>
{% endmacro %}

{% block javascripts %}
    <script>

    </script>
{% endblock %}

templates/meeting/weekend/program/_outgoing_speech_modal.html.twig
<div class="modal fade" id="modalOutgoing__name__" data-id="modalOutgoing__name__" tabindex="-1" role="dialog" aria-labelledby="modalOutgoing__name__Label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Orateur(s) sortant</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body modal-outgoing"
                 data-prototype="{{ _self.outgoing_prototype(f.outgoing.vars.prototype)|e }}"
                 data-weekend-id="__name__"
            >
                {% for form in f.outgoing %}
                    <div class="input-group mb-4">
                        {{ form_widget(p.congregation, { 'attr': { 'placeholder': 'Nom de l\'assemblée' } }) }}
                        {{ form_widget(p.speaker) }}
                        {{ form_widget(p.speech) }}
                        <a href="#" class="btn btn-outline-danger ml-2 remove-outgoing-speaker"><i class="fas fa-trash"></i></a>
                    </div>
                {% endfor %}
            </div>

            <div class="modal-footer">
                <a href="#"
                   class="add-speaker btn btn-primary"
                   data-weekend-id="__name__"
                >
                    Ajout orateur sortant
                </a>
            </div>
        </div>
    </div>
</div>

{% macro outgoing_prototype(p) %}
    <div class="input-group mb-4">
        {{ form_widget(p.congregation, { 'attr': { 'placeholder': 'Nom de l\'assemblée' } }) }}
        {{ form_widget(p.speaker) }}
        {{ form_widget(p.speech) }}
        <a href="#" class="btn btn-outline-danger ml-2 remove-outgoing-speaker"><i class="fas fa-trash"></i></a>
    </div>
{% endmacro %}

templates/meeting/weekend/program/_show_ajax.html.twig
<div class="buttons_action mb-4">
    <a href="{{ path('program_show', {'id': program.id, 'pdf': true}) }}" class="btn"><i class="fas fa-file-pdf mr-2"></i>Télécharger en PDF</a>

</div>
<div class="content">
{% for w in program.weekends %}
    <table class="table">
        <thead class="thead-mint">
        <tr>
            <th scope="col" class="program-date">{{ w.date|date('d/m/Y') }}</th>
            {% if w.type ==  constant('App\\Meeting\\Weekend\\Entity\\Weekend::TYPE_OVERSEER') %}
                <th scope="col" >Semaine spéciale</th>
            {%  elseif w.type == constant('App\\Meeting\\Weekend\\Entity\\Weekend::TYPE_CONVENTION') %}
                <th scope="col" >Week-end d'assemblée</th>
            {%  else %}
                <th scope="col" >{{ w.speech.number }} - {{ w.speech.title }}</th>
            {% endif %}
        </tr>
        </thead>
        {% if w.type != constant('App\\Meeting\\Weekend\\Entity\\Weekend::TYPE_CONVENTION') %}
            <tbody>
            <tr>
                <td><b>Orateur</b></td>
                {% if w.type == constant('App\\Meeting\\Weekend\\Entity\\Weekend::TYPE_OVERSEER') %}
                    <td>{{ w.overseerName }}</td>
                {% endif %}
                {% if w.type == constant('App\\Meeting\\Weekend\\Entity\\Weekend::TYPE_EXTERNAL_SPEAKER') %}
                    <td>{{ w.externalName }}</td>
                {% endif %}
                {% if w.type is null %}
                    <td>{{ w.speaker }}</td>
                {% endif %}
            </tr>
            <tr>
                <td><b>Président</b></td>
                <td>{{ w.chairman }}</td>
            </tr>
            {% if w.type != constant('App\\Meeting\\Weekend\\Entity\\Weekend::TYPE_OVERSEER') %}
                <tr>
                    <td><b>Lecteur</b></td>
                    <td>{{ w.reader }}</td>
                </tr>
            {% endif %}

            {% if w.outgoingSpeeches is not empty %}
                <tr>
                    <td>Orateur(s) sortant</td>
                    <td>
                        {% for talk in w.outgoingSpeeches %}
                            <small>{{ talk.speaker }} ({{ talk.congregation }})  <i>{{ talk.speech }}</i></small>
                            <br>
                        {% endfor %}
                    </td>
                </tr>
            {% endif %}
            </tbody>
        {% endif %}
    </table>
{% endfor %}
</div>

templates/meeting/weekend/program/list.html.twig
{% extends 'base.html.twig' %}

{% set navCurrent = 'programs' %}

{% block page_title %}Réunions du week-end{% endblock %}

{% block page_sub_title %}Programmes{% endblock %}


{% block breadcrumb %}
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('dashboard') }}">Tableau de bord</a></li>
            <li class="breadcrumb-item active" aria-current="page">Réunions du week-end</li>
        </ol>
    </nav>
{% endblock breadcrumb %}

{% block body %}

    <div class="body-content mt-4">

        {% for message in app.flashes('success') %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <span class="icon-check-circle mr-2"></span>
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}

        <div class="card">
            <div class="card-body">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Période</th>
                        <th scope="col">Date création</th>
                        <th scope="col">Dernière modif.</th>
                        <th scope="col">Créé par</th>
                        <td>Status</td>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for p in programs %}
                        <tr>
                            <td>
                                {{p.startDate|localizeddate('full', 'full', 'FR_fr', 'Europe/Paris', 'MMMM Y')|capitalize }}
                            </td>
                            <td>{{ p.createdAt|date('d/m/Y') }}</td>
                            <td>
                                {% if p.updatedAt != null %}
                                    {{ p.updatedAt|date('d/m/Y') }}
                                {% endif %}
                            </td>
                            <td>{{ p.user.person.firstName }} {{ p.user.person.lastName }}</td>
                            {% if p.draft %}
                                <td><span class="badge badge-secondary">brouillon <i class="fas fa-pencil-ruler ml-2"></i></span></td>
                                {% else %}
                                    <td><span class="badge badge-success">validé <i class="fas fa-check ml-2"></i></span></td>
                            {% endif %}

                            <td>
                                {% if p.draft == false %}
                                    <a href="{{ path('program_show', {'id': p.id}) }}" class="btn btn-primary"><i class="fas fa-eye mr-2"></i>OUVRIR</a>
                                {% endif %}
                                <a href="{{ path('program_edit', {'id': p.id}) }}" class="btn btn-warning"><i class="fas fa-pencil-alt mr-2"></i>MODIFIER</a>
                                <a href="{{ path('program_remove', {'id': p.id}) }}" class="btn btn-danger"><i class="fas fa-pencil-alt mr-2"></i>SUPPRIMER</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div id="button_add">
        <button type="button" class="btn btn-add btn-danger" data-toggle="modal" data-target="#createProgram">
            <i class="fas fa-plus"></i>
        </button>

    </div>

{% endblock body %}

{% block modal %}
<!-- Modal -->
<div class="modal fade" id="createProgram" tabindex="-1" role="dialog" aria-labelledby="createProgramLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createProgramLabel">Création d'un nouveau programme</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="month">Choix du mois</label>
                    <select name="month" id="month" class="form-control">
                        <option value="" disabled selected>Sélectionner un mois</option>
                        <option value="01">Janvier</option>
                        <option value="02">Février</option>
                        <option value="03">Mars</option>
                        <option value="04">Avril</option>
                        <option value="05">Mai</option>
                        <option value="06">Juin</option>
                        <option value="07">Juillet</option>
                        <option value="08">Août</option>
                        <option value="09">Septembre</option>
                        <option value="10">Octobre</option>
                        <option value="11">Novembre</option>
                        <option value="12">Décembre</option>
                    </select>
                </div>
                <div class="form-group mt-4">
                    <label for="year">Choix de l'année</label>
                    <select name="year" id="year" class="form-control">
                        <option value="" disabled selected>Sélectionner une année</option>
                        <option value="2021">2021</option>
                        <option value="2022">2022</option>
                        <option value="2023">2023</option>
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <a href="#" id="validate" class="btn btn-primary">Créer un programme</a>
            </div>
        </div>
    </div>
</div>
{% endblock modal %}

{% block javascripts %}
    {{ encore_entry_script_tags('generate-program') }}
{% endblock javascripts %}