src/Core/Entity/Person.php
<?php

namespace App\Core\Entity;

use App\Core\Repository\PersonRepository;
use App\Meeting\Weekend\Entity\Chairman;
use App\Meeting\Weekend\Entity\OutgoingSpeech;
use App\Meeting\Weekend\Entity\Reader;
use App\Meeting\Weekend\Entity\Speaker;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PersonRepository::class)
 */
class Person
{
    const MALE = 'M';
    const FEMALE = 'F';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank(message="Ce champ ne doit pas être vide")
     * @Groups({"list", "show"})
     * @ORM\Column(type="string", length=128)
     */
    private $first_name;

    /**
     * @Assert\NotBlank(message="Ce champ ne doit pas être vide")
     * @Groups({"list", "show"})
     * @ORM\Column(type="string", length=128)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     */
    private $cell_phone;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     */
    private $home_phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address_line_1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address_line_2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address_line_3;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthday;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $baptism_day;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_baptized;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_elder;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_servant;

    /**
     * @ORM\Column(type="string", length=2)
     */
    private $gender = self::MALE;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * @var User
     * @ORM\OneToOne(mappedBy="person", targetEntity="App\Core\Entity\User")
     */
    private $user;

    /**
     * @Groups({"list", "show"})
     * @var Speaker
     * @ORM\OneToOne(targetEntity=Speaker::class, cascade={"persist", "remove"}, mappedBy="person")
     */
    private $speaker;

    /**
     * @var Reader
     * @ORM\OneToOne(targetEntity=Reader::class, cascade={"persist", "remove"}, mappedBy="person")
     */
    private $reader;

    /**
     * @var Chairman
     * @ORM\OneToOne(targetEntity=Chairman::class, cascade={"persist", "remove"}, mappedBy="person")
     */
    private $chairman;

    /**
     * @var bool
     */
    private $isSpeaker;

    /**
     * @var bool
     */
    private $isWtReader;

    /**
     * @var bool
     */
    private $isChairman;

    /**
     * @var bool
     */
    private $isOutgoingSpeaker;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCellPhone(): ?string
    {
        return $this->cell_phone;
    }

    public function setCellPhone(?string $cell_phone): self
    {
        $this->cell_phone = $cell_phone;

        return $this;
    }

    public function getHomePhone(): ?string
    {
        return $this->home_phone;
    }

    public function setHomePhone(?string $home_phone): self
    {
        $this->home_phone = $home_phone;

        return $this;
    }

    public function getAddressLine1(): ?string
    {
        return $this->address_line_1;
    }

    public function setAddressLine1(?string $address_line_1): self
    {
        $this->address_line_1 = $address_line_1;

        return $this;
    }

    public function getAddressLine2(): ?string
    {
        return $this->address_line_2;
    }

    public function setAddressLine2(?string $address_line_2): self
    {
        $this->address_line_2 = $address_line_2;

        return $this;
    }

    public function getAddressLine3(): ?string
    {
        return $this->address_line_3;
    }

    public function setAddressLine3(?string $address_line_3): self
    {
        $this->address_line_3 = $address_line_3;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(?\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getBaptismDay(): ?\DateTimeInterface
    {
        return $this->baptism_day;
    }

    public function setBaptismDay(?\DateTimeInterface $baptism_day): self
    {
        $this->baptism_day = $baptism_day;

        return $this;
    }

    public function getIsBaptized(): ?bool
    {
        return $this->is_baptized;
    }

    public function setIsBaptized(?bool $is_baptized): self
    {
        $this->is_baptized = $is_baptized;

        return $this;
    }

    public function getIsElder(): ?bool
    {
        return $this->is_elder;
    }

    public function setIsElder(?bool $is_elder): self
    {
        $this->is_elder = $is_elder;

        return $this;
    }

    public function getIsServant(): ?bool
    {
        return $this->is_servant;
    }

    public function setIsServant(?bool $is_servant): self
    {
        $this->is_servant = $is_servant;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): self
    {
        $this->gender = self::MALE;

        return $this;
    }

    public function __toString()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?\DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    /**
     * @return User
     */
    public function getUser(): User
    {
        return $this->user;
    }

    /**
     * @param User $user
     */
    public function setUser(User $user): void
    {
        $this->user = $user;
    }

    /**
     * @return Speaker
     */
    public function getSpeaker(): ?Speaker
    {
        return $this->speaker;
    }

    /**
     * @param Speaker $speaker
     */
    public function setSpeaker(Speaker $speaker): void
    {
        $this->speaker = $speaker;
    }

    /**
     * @return Reader
     */
    public function getReader(): ?Reader
    {
        return $this->reader;
    }

    /**
     * @param Reader|null $reader
     */
    public function setReader(?Reader $reader): void
    {
        $this->reader = $reader;
    }

    public function getIsSpeaker(): bool
    {
        return $this->getSpeaker() !== null ? $this->getSpeaker()->getIsActive() : false;
    }

    public function setIsSpeaker($isSpeaker)
    {
        if ($this->getSpeaker()) {
            $this->getSpeaker()->setIsActive($isSpeaker);
        } else {
            $speaker = new Speaker();
            $speaker->setPerson($this);
            $this->setSpeaker($speaker);
        }

    }

    /**
     * @return bool
     */
    public function getIsWtReader(): bool
    {
        return $this->getReader() !== null ? $this->getReader()->getIsActive() : false;
    }

    /**
     * @param bool $isWtReader
     */
    public function setIsWtReader(bool $isWtReader): void
    {
        if($this->getReader()) {
            $this->getReader()->setIsActive($isWtReader);
        } else {
            $reader = new Reader();
            $reader->setPerson($this);
            $this->setReader($reader);
        }

    }

    /**
     * @return mixed
     */
    public function getIsChairman()
    {
        return $this->getChairman() !== null ? $this->getChairman()->getIsActive() : false;
    }

    /**
     * @param mixed $isChairman
     */
    public function setIsChairman($isChairman): void
    {
        if ($this->getChairman()) {
            $this->getChairman()->setIsActive($isChairman);
        } else {
            $chairman = new Chairman();
            $chairman->setPerson($this);
            $this->setChairman($chairman);
        }

    }

    /**
     * @return mixed
     */
    public function getIsOutgoingSpeaker()
    {
        return $this->getSpeaker() !== null && $this->getSpeaker()->isOutgoing();
    }

    /**
     * @param mixed $isOutgoingSpeaker
     */
    public function setIsOutgoingSpeaker($isOutgoingSpeaker): void
    {
        $this->speaker->setIsOutgoing($isOutgoingSpeaker);

    }

    /**
     * @return Chairman
     */
    public function getChairman(): ?Chairman
    {
        return $this->chairman;
    }

    /**
     * @param Chairman $chairman
     */
    public function setChairman(Chairman $chairman): void
    {
        $this->chairman = $chairman;
    }



}

src/Core/Form/PersonType.php
<?php

namespace App\Core\Form;

use App\Core\Entity\Person;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('first_name', null, [
                'label' => 'Prénom',
                'required' => true
            ])
            ->add('last_name', null, [
                'label' => 'Nom',
                'required' => true
            ])
            ->add('email', EmailType::class, [
                'label' => 'Email',
                'required' => false
            ])
            ->add('cell_phone', null, [
                'label' => 'N° téléphone portable',
            ])
            ->add('home_phone', null, [
                'label' => 'N° téléphone domicile',
            ])
            ->add('address_line_1', null, [
                'label' => 'Adresse ligne 1',
            ])
            ->add('address_line_2', null, [
                'label' => 'Adresse ligne 2',
            ])
            ->add('address_line_3', null, [
                'label' => 'Adresse ligne 3',
            ])
            ->add('birthday', DateType::class, [
                'html5' => true,
                'widget' => 'single_text',
                'label' => 'Date de naissance',
                'required' => false
            ])
            ->add('baptism_day', DateType::class, [
                'html5' => true,
                'widget' => 'single_text',
                'label' => 'Date de baptême',
                'required' => false
            ])
            ->add('is_baptized', CheckboxType::class, [
                'label' => 'Baptisé',
                'required' => false
            ])
            ->add('is_elder', CheckboxType::class, [
                'label' => 'Ancien',
                'required' => false
            ])
            ->add('is_servant', CheckboxType::class, [
                'label' => 'Assistant',
                'required' => false
            ])
            ->add('gender', ChoiceType::class, [
                'choices' => [
                    'Homme' => 'M',
                    'Femme' => 'F'
                ],
                'label' => 'Genre'
            ])
            ->add('isSpeaker', CheckboxType::class, [
                'attr' => ['class' => 'isSpeaker'],
                'mapped' => true,
                'required' => false
            ])
            ->add('isWtReader', CheckboxType::class, [
                'attr' => ['class' => 'isWtReader'],
                'mapped' => true,
                'required' => false,
            ])
            ->add('isChairman', CheckboxType::class, [
                'attr' => ['class' => 'isChairman'],
                'mapped' => true,
                'required' => false
            ])
            ->add('isOutgoingSpeaker', CheckboxType::class, [
                'attr' => ['class' => 'isOutgoingSpeaker'],
                'required' => false,
                'mapped' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Person::class,
        ]);
    }
}

src/Core/Controller/PersonController.php
<?php


namespace App\Core\Controller;


use App\Core\Entity\Person;
use App\Core\Form\PersonType;
use App\Meeting\Weekend\Service\BrotherAssignment;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\ConstraintViolationInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * @Route("/dashboard/persons")
 * Class PersonController
 * @package App\Core\Controller
 */
class PersonController extends AbstractController
{
    /** @var EntityManagerInterface $em */
    private $em;

    private $assignmentService;

    public function __construct(EntityManagerInterface $em, BrotherAssignment $assignmentService)
    {
        $this->em = $em;
        $this->assignmentService = $assignmentService;
    }


    /**
     * @Route("/list", name="person_list")
     * @return Response
     */
    public function list(PaginatorInterface $paginator, Request $request)
    {
        /** @var Person[] $persons */
        $persons = $this->em->getRepository(Person::class)->findBy(['deletedAt' => null], ['last_name' => 'ASC']);
        $pagination = $paginator->paginate(
            $persons,
            $request->query->getInt('page', 1),
            10
        );
        $form = $this->buildForm(new Person());

        return $this->render('person/list.html.twig', [
            'persons' => $pagination,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/edit/{id}", name="person_edit")
     * @param Person $person
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function edit(Person $person, Request $request)
    {
        $form = $this->buildForm($person);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->flush();
            $this->addFlash('success', 'Le proclamateur a été modifié.');
            return $this->redirectToRoute('person_list');
        }

        return $this->render('person/edit.html.twig', [
            'form' => $form->createView(),
            'person' => $person
        ]);

    }

    /**
     * @Route("/delete/{id}", name="person_remove")
     * @param Person $person
     * @return RedirectResponse
     */
    public function delete(Person $person)
    {
        $person->setDeletedAt(new \DateTime());
        $this->em->flush();
        $this->addFlash('success', 'Le proclamateur a été marqué comme supprimé.');
        return $this->redirectToRoute('person_list');
    }

    private function buildForm(Person $person)
    {
        $form = $this->createForm(PersonType::class, $person);
        return $form;
    }

    /**
     * @Route("/save", name="person_save")
     * @param Request $request
     * @return JsonResponse|RedirectResponse
     */
    public function save(Request $request, ValidatorInterface $validator)
    {
        $person = new Person();
        $form = $this->buildForm($person);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $this->em->persist($person);
            $this->em->flush();
            $this->addFlash('success', 'Un nouveau proclamateur a été ajouté.');
            return new JsonResponse('OK');
        }

        $errors = $validator->validate($person);
        $response = [];


        if (count($errors) > 0) {
            /** @var ConstraintViolationInterface $error */
            foreach ($errors as $error) {
                $response[] = [
                  'property' => $error->getPropertyPath(),
                  'message' => $error->getMessage()
                ];
            }
        }



        return new JsonResponse($response, Response::HTTP_BAD_REQUEST);

    }

}

templates/person/edit.html.twig
{% extends 'base.html.twig' %}
{% set navCurrent = 'persons' %}
{% block page_title %}Proclamateurs{% endblock %}

{% block page_sub_title %}{{ person.firstName }} {{ person.lastName }}{% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('dashboard') }}">Tableau de bord</a></li>
            <li class="breadcrumb-item"><a href="{{ path('person_list') }}">Proclamateurs</a></li>
            <li class="breadcrumb-item active" aria-current="page">Modifications</li>
        </ol>
    </nav>
{% endblock breadcrumb %}

{% block body %}

    <form action="{{ path('person_edit', {'id': person.id}) }}" method="post">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                {{ form_label(form.first_name) }}
                                {{ form_widget(form.first_name) }}
                            </div>
                            <div class="col-md-6">
                                {{ form_label(form.last_name) }}
                                {{ form_widget(form.last_name) }}
                            </div>
                        </div>
                        <div class="row mt-4">
                            <div class="col-md-6">
                                {{ form_label(form.email) }}
                                {{ form_widget(form.email) }}
                            </div>
                          <!--  <div class="col-md-6">
                                {{ form_label(form.gender) }}
                                {{ form_widget(form.gender) }}
                            </div> -->
                        </div>
                      <!--  <div class="row mt-4">
                            <div class="col-md-6">
                                {{ form_label(form.cell_phone) }}
                                {{ form_widget(form.cell_phone) }}
                            </div>
                            <div class="col-md-6">
                                {{ form_label(form.home_phone) }}
                                {{ form_widget(form.home_phone) }}
                            </div>
                        </div>
                        <div class="row mt-4">
                            <div class="col-md-12">
                                {{ form_label(form.address_line_1) }}
                                {{ form_widget(form.address_line_1) }}
                            </div>
                        </div>
                        <div class="row mt-4">
                            <div class="col-md-12">
                                {{ form_label(form.address_line_2) }}
                                {{ form_widget(form.address_line_2) }}
                            </div>
                        </div>
                        <div class="row mt-4">
                            <div class="col-md-12">
                                {{ form_label(form.address_line_3) }}
                                {{ form_widget(form.address_line_3) }}
                            </div>
                        </div>
                        <div class="row mt-4">
                            <div class="col-md-4">
                                {{ form_label(form.birthday) }}
                                {{ form_widget(form.birthday) }}
                            </div>
                            <div class="col-md-4">
                                {{ form_label(form.baptism_day) }}
                                {{ form_widget(form.baptism_day) }}
                            </div>
                        </div>-->
                        <div class="row mt-4">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form_label(form.isSpeaker) }}
                                    {{ form_widget(form.isSpeaker) }}
                                </div>
                                <div class="form-group">
                                    {{ form_label(form.isWtReader) }}
                                    {{ form_widget(form.isWtReader) }}
                                </div>
                                <div class="form-group">
                                    {{ form_label(form.isOutgoingSpeaker) }}
                                    {{ form_widget(form.isOutgoingSpeaker) }}
                                </div>
                                <div class="form-group">
                                    {{ form_label(form.isChairman) }}
                                    {{ form_widget(form.isChairman) }}
                                </div>
                            </div>
                        </div>

                        <div class="row mt-4">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-indigo-dye">
                                    <span class="icon-check-circle mr-2"></span> valider
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {{ form_widget(form._token) }}
    </form>
{% endblock body %}

templates/person/list.html.twig
{% extends 'base.html.twig' %}

{% set navCurrent = 'persons' %}
{% block page_title %}Proclamateurs{% endblock %}

{% block page_sub_title %}{{ assemby_name }}{% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('dashboard') }}">Tableau de bord</a></li>
            <li class="breadcrumb-item active" aria-current="page">Proclamateurs</li>
        </ol>
    </nav>
{% endblock breadcrumb %}

{% block body %}


    <div class="body-content mt-4">
        {% for message in app.flashes('success') %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <span class="icon-check-circle mr-2"></span>
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}

        <div class="card">
            <div class="card-body">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Nom</th>
                        <th scope="col">Email</th>
                        <th scope="col">Téléphone</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for p in persons %}
                        <tr>
                            <td>{{ p.firstName }} {{ p.lastName|upper }}</td>
                            <td>{{ p.email }}</td>
                            <td>{{ p.cellPhone }}</td>
                            <td>
                                <a href="{{ path('person_edit', {'id': p.id}) }}" class="btn btn-warning"><i class="fas fa-pencil-alt mr-2"></i>MODIFIER</a>

                               {% if app.user.person != p %}
                               <button type="button" class="btn btn-red" data-toggle="modal" data-target="#personDeletion-{{ p.id }}">
                                   <i class="fas fa-times mr-2"></i>DESACTIVER
                               </button>
                               {% endif %}
                               </td>

                        </tr>

                        {# Modal for person deletion #}
                        <div class="modal fade" id="personDeletion-{{ p.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Désactiver un proclamateur</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>
                                            Veux tu vraiment désactiver <b>{{ p.firstName }} {{ p.lastName }}</b> ?
                                        </p>
                                            <a href="{{ path('person_remove', {'id': p.id}) }}" class="btn btn-red">VALIDER</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="navigation">
                    {{ knp_pagination_render(persons) }}
                </div>
            </div>
        </div>
    </div>

    <div id="button_add" data-toggle="modal" data-target="#modalSave">
        <span class="btn btn-add btn-red"><span class="fas fa-plus"></span></span>
    </div>


    {# MODAL SAVE PERSON #}
    <div class="modal modal-fluid fade modal-person" id="modalSave" tabindex="-1" role="dialog" aria-hidden="true">
        {% include 'person/_save.html.twig' %}
    </div>
{% endblock body %}

{% block javascripts %}
    {{ encore_entry_script_tags('person') }}
{% endblock %}